import { FirebaseService } from '../integrations/firebase/firebase.service.js';
import { EmployeeActivity } from '../interfaces/index.js';

export class ActivityService {
    static async logActivity(
        businessId: string,
        employeeId: string,
        action: string,
        entityId?: string,
        details?: string
    ): Promise<void> {
        const activity: EmployeeActivity = {
            id: '', // Will be generated by FirebaseService
            businessId,
            employeeId,
            action,
            entityId,
            timestamp: new Date(),
            details
        };

        return FirebaseService.logActivity(businessId, activity);
    }
}
